### ISSUE TITLE
Recaptcha Visibility

### ISSUE THREAD

**Issue by Jason-Cooke** [t49tran/react-google-recaptcha-v3#10]
Hi, 

Just wondering if you have any plans to add a visibility prop to **react-google-recaptcha-v3**?
You have a really great component here, but in order for me to use it. I'm going to need to make
it **invisible**

Thanks for your time!

**Comment by lynscott** [comment]
Kind of related to @Jason-Cooke 's issue, but the visibility of the recaptcha badge seems to linger after leaving the associated page unless you refresh the page.

IE I want the recaptcha badge and associated actions present on a login form but it shouldn't be visible throughout the entire application. Unless that is the expected behavior with your wrapper?
