### ISSUE TITLE
How to interpret recieved token?

### ISSUE THREAD

**Issue by 1ivanr33** [t49tran/react-google-recaptcha-v3#2]
What should I do after getting token to verify if the user is not robot and to allow or decline his action?

**Comment by t49tran** [comment]
The token should be sent to your backend, which in turn, will call Google Service itself to determine whether the user is trustworthy or not.

The process is pretty well documented by Google themselves and you can find it here:

https://developers.google.com/recaptcha/docs/v3

I will close this issue as it's more of a question rather than an issue with the library.
