### ISSUE TITLE
how to reset recaptcha ? 

### ISSUE THREAD

**Issue by sumarsanaadi** [t49tran/react-google-recaptcha-v3#5]
I installed the module in react Single Page Apps, the problem is I need to use the recaptcha only on 2 pages (e.g register and contact). but the token only generated once .

**Comment by t49tran** [comment]
As per the Google doc for Recaptcha V3, the reset function is not mentioned: https://developers.google.com/recaptcha/docs/v3. However, if you deep dive enough and play with the recaptcha instance provided, there is a `reset` function. As it's not mentioned in the official doc, I don't provide support for that.

There are multiple ways to have different recaptcha token on different pages of a SPA. You can either have instances of  `<GoogleRecaptcha />` on each pages, or you can use the hook or the HOC to inject the `executeRecaptcha` function to each pages and generate the token when it's required.

I will close this issue as it's a question rather than an issue.
