### ISSUE TITLE
executeRecaptcha is undeifned

### ISSUE THREAD

**Issue by jaydenlin** [t49tran/react-google-recaptcha-v3#57]
Thank you for providing the wrapper to use the recaptcha-v3.

However, I followed the guide here, and I got `TypeError: executeRecaptcha is not a function`. Could you help ?
```
import {
  GoogleReCaptchaProvider,
  useGoogleReCaptcha
} from 'react-google-recaptcha-v3';
 
const YourReCaptchaComponent  = () => {
  const { executeRecaptcha } = useGoogleReCaptcha();
  const token = executeRecaptcha("login_page");
 
  return (<div></div>)
}
 
ReactDom.render(
  <GoogleReCaptchaProvider reCaptchaKey="[Your recaptcha key]">
    <YourReCaptchaComponent />
  </GoogleReCaptchaProvider>,
  document.getElementById('app')
);
```

**Comment by Mosquid** [comment]
@jaydenlin for me the problem was that I didn't wrap my component into reCaptcha provider

**Comment by t49tran** [comment]
@jaydenlin Could you provide your code that having the issue ? What @Mosquid said is actually also a common mistake people make from time to time.

**Comment by eabdollahian** [comment]
I get the same error. And When I log executeRecaptcha this shows me.
`ƒ (e){if(!C||!C.execute)throw new Error("<GoogleReCaptchaProvider /> Google Recaptcha has not been loaded");return C.execute(x.current,{action:e})}`
I used this trick and I think the problem is gone:
` 
const handleRecaptcha = useCallback(async () => {
 if (!executeRecaptcha) {
      console.log("Execute recaptcha not yet available");
      return;
    }
try {
      const token = await executeRecaptcha("homepage");
      console.log("token", token);
      if (token) {
//do sth
    }
} catch (e) {
      console.log(e);
      setTimeout(() => handleRecaptcha(), 100);
    }
},[executeRecaptcha]);`
