### ISSUE TITLE
Cannot build with 1.9.1+

### ISSUE THREAD

**Issue by michalbundyra** [t49tran/react-google-recaptcha-v3#74]
I am using react-google-recaptcha-v3 in my project and all worked fine up to 1.9.0 version.
Today tried update to the latest version and got the following error:

```
Type error: Could not find a declaration file for module 'react-google-recaptcha-v3'. '/MY_PATH/node_modules/react-google-recaptcha-v3/dist/react-google-recaptcha-v3.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-google-recaptcha-v3` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-google-recaptcha-v3';`
```

but there is no `@types/react-google-recaptcha-v3` package, and it was not needed in version 1.9.0.
The problem is since 1.9.1 version.

I am using TypeScript in my project. Thanks

**Comment by t49tran** [comment]
Hi @michalbundyra, thanks for reporting the error.

It has been fixed with the latest version 1.9.4. I have also deprecated all version from 1.9.1 to 1.9.3.

Recently, I have tried to update the build to rollup@v2 in order to make use of React 17 and attempting to reduce the bundle size. I didn't realise that the @rollup/plugin-typescript doesn't emit the type yet.

I have reverted back those changes. Sorry for the inconvenience.
