### ISSUE TITLE
`recaptcha__xx.js` script is loaded twice

### ISSUE THREAD

**Issue by matiishyn** [t49tran/react-google-recaptcha-v3#82]
### steps to reproduce
1. start a new CRA app by `npx create-react-app my-app`
2. add `GoogleReCaptchaProvider` as described in docs, make sure you paste your `recaptcha key`
![image](https://user-images.githubusercontent.com/3661065/118991943-d8df3980-b98c-11eb-9bbb-a12de3fac178.png)
3. start the app and open Network devtools

### Actual result
`recaptcha__en.js` script is loaded twice
![image](https://user-images.githubusercontent.com/3661065/118992619-7a668b00-b98d-11eb-8388-c7a28faaf6e5.png)

### Expected result
`recaptcha__en.js` script should is loaded twice

### versions used
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-google-recaptcha-v3": "^1.9.4",
    "react-scripts": "4.0.3",
```
macOS, Google Chrome 90

**Comment by t49tran** [comment]
Hi @matiishyn , thanks for reporting, I will have a look.

**Comment by t49tran** [comment]
Hi @matiishyn, after some investigation it turns out that it's a problem with Google recaptcha script, not this library.

In your screenshot, the script injected by `react-google-recaptcha-v3` is the `api.js` right above the two `recaptcha__en.js`. That script from Google will then inject the `recaptcha_en.js` and as it is from Google. It's out of my control.

People have reported this issue with Google but they haven't fixed it. You can have a look here: https://github.com/google/recaptcha/issues/236.

Thanks for reporting this but I will close this issue for now.
